# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'editor_settings.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 124)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(30, 80, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.editor_path = QtWidgets.QLineEdit(Dialog)
        self.editor_path.setGeometry(QtCore.QRect(30, 40, 251, 20))
        self.editor_path.setObjectName("editor_path")
        self.choose_button = QtWidgets.QPushButton(Dialog)
        self.choose_button.setGeometry(QtCore.QRect(300, 40, 75, 23))
        self.choose_button.setObjectName("choose_button")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(30, 20, 71, 16))
        self.label.setObjectName("label")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        self.choose_button.clicked.connect(self.choose_dir)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.choose_button.setText(_translate("Dialog", "Choose"))
        self.label.setText(_translate("Dialog", "Editor Path:"))

    def choose_dir(self):
        file = QtWidgets.QFileDialog()
        fn = file.exec()
        if(fn):
            try:
                self.editor_path.setText(file.selectedFiles()[0])
            except:
                print(sys.exc_info()[0])