# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'new_project.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(366, 292)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(10, 230, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.project_name = QtWidgets.QLineEdit(Dialog)
        self.project_name.setGeometry(QtCore.QRect(20, 30, 331, 20))
        self.project_name.setObjectName("project_name")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(20, 10, 111, 16))
        self.label.setObjectName("label")
        self.project_directory = QtWidgets.QLineEdit(Dialog)
        self.project_directory.setGeometry(QtCore.QRect(20, 90, 241, 20))
        self.project_directory.setObjectName("project_directory")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(20, 60, 101, 16))
        self.label_2.setObjectName("label_2")
        self.choose_directory = QtWidgets.QPushButton(Dialog)
        self.choose_directory.setGeometry(QtCore.QRect(280, 90, 75, 23))
        self.choose_directory.setObjectName("choose_directory")
        self.window_x = QtWidgets.QLineEdit(Dialog)
        self.window_x.setGeometry(QtCore.QRect(20, 150, 41, 20))
        self.window_x.setObjectName("window_x")
        self.window_y = QtWidgets.QLineEdit(Dialog)
        self.window_y.setGeometry(QtCore.QRect(70, 150, 41, 20))
        self.window_y.setObjectName("window_y")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(20, 130, 47, 13))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(70, 130, 47, 13))
        self.label_4.setObjectName("label_4")
        self.ticks_per_second = QtWidgets.QLineEdit(Dialog)
        self.ticks_per_second.setGeometry(QtCore.QRect(220, 150, 41, 20))
        self.ticks_per_second.setObjectName("ticks_per_second")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(130, 150, 91, 16))
        self.label_5.setObjectName("label_5")
        self.game_title = QtWidgets.QLineEdit(Dialog)
        self.game_title.setGeometry(QtCore.QRect(20, 200, 331, 20))
        self.game_title.setObjectName("game_title")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(20, 173, 81, 20))
        self.label_6.setObjectName("label_6")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        self.choose_directory.clicked.connect(self.choose_dir)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "New Project"))
        self.label.setText(_translate("Dialog", "Project Name:"))
        self.label_2.setText(_translate("Dialog", "Project Directory:"))
        self.choose_directory.setText(_translate("Dialog", "Choose"))
        self.label_3.setText(_translate("Dialog", "Width:"))
        self.label_4.setText(_translate("Dialog", "Height:"))
        self.label_5.setText(_translate("Dialog", "Ticks per second"))
        self.label_6.setText(_translate("Dialog", "Game Title:"))

    def choose_dir(self):
        file = QtWidgets.QFileDialog()
        file.setFileMode(QtWidgets.QFileDialog.FileMode.DirectoryOnly)
        fn = file.exec()
        if(fn):
            try:
                self.project_directory.setText(file.selectedFiles()[0])
            except:
                print(sys.exc_info()[0])