# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'new_gameobject.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 198)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(-70, 150, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gameobject_type_name = QtWidgets.QLineEdit(Dialog)
        self.gameobject_type_name.setGeometry(QtCore.QRect(20, 50, 351, 20))
        self.gameobject_type_name.setObjectName("gameobject_type_name")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(20, 30, 171, 16))
        self.label.setObjectName("label")
        self.gameobject_image_directory = QtWidgets.QLineEdit(Dialog)
        self.gameobject_image_directory.setGeometry(QtCore.QRect(20, 100, 271, 20))
        self.gameobject_image_directory.setObjectName("gameobject_image_directory")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(20, 80, 201, 16))
        self.label_2.setObjectName("label_2")
        self.choose_button = QtWidgets.QPushButton(Dialog)
        self.choose_button.setGeometry(QtCore.QRect(300, 100, 75, 23))
        self.choose_button.setObjectName("choose_button")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        self.choose_button.clicked.connect(self.choose_dir)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "GameObject type name"))
        self.label_2.setText(_translate("Dialog", "GameObject image directory"))
        self.choose_button.setText(_translate("Dialog", "Choose"))
		
    def choose_dir(self):
        file = QtWidgets.QFileDialog()
        fn = file.exec()
        if(fn):
            try:
                self.gameobject_image_directory.setText(file.selectedFiles()[0])
            except:
                print(sys.exc_info()[0])
