# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'new_scene.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 176)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(30, 140, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.scene_name = QtWidgets.QLineEdit(Dialog)
        self.scene_name.setGeometry(QtCore.QRect(20, 40, 341, 20))
        self.scene_name.setObjectName("scene_name")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(20, 20, 81, 16))
        self.label.setObjectName("label")
        self.background_image_dir = QtWidgets.QLineEdit(Dialog)
        self.background_image_dir.setGeometry(QtCore.QRect(20, 90, 261, 20))
        self.background_image_dir.setObjectName("background_image_dir")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(20, 70, 111, 16))
        self.label_2.setObjectName("label_2")
        self.choose_directory = QtWidgets.QPushButton(Dialog)
        self.choose_directory.setGeometry(QtCore.QRect(290, 90, 75, 23))
        self.choose_directory.setObjectName("choose_directory")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        self.choose_directory.clicked.connect(self.choose_dir)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "New Scene"))
        self.label.setText(_translate("Dialog", "Scene Name:"))
        self.label_2.setText(_translate("Dialog", "Background Image"))
        self.choose_directory.setText(_translate("Dialog", "Choose"))
		
    def choose_dir(self):
        file = QtWidgets.QFileDialog()
        fn = file.exec()
        if(fn):
            try:
                self.background_image_dir.setText(file.selectedFiles()[0])
            except:
                print(sys.exc_info()[0])